
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module sound_sample(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT
	
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire en;
wire clk_i2c;
wire reset;
wire [15:0] audiodata;

reg nextdata_n;
//wire [7:0] data;
//reg [7:0]kbdata; 
wire ready;
wire overflow; // fifo overflow

wire [6:0]volume;
wire [15:0]freq;

wire [2:0]audio_config_testbits;
wire audio_clk_sig;
//reg myclk;
//=======================================================
//  Structural coding
//=======================================================

assign reset = ~KEY[0];

audio_clk u1(CLOCK2_50, reset,AUD_XCK, audio_clk_sig);


//always @ (posedge PS2_CLK)
//begin
//	if(ready)
//	begin
//		kbdata <= data;
//		nextdata_n <= 0;
//	end
//	else begin
//		kbdata <= kbdata;
//		nextdata_n <= 1;
//	end
//end

//I2C part
clkgen #(10000) my_i2c_clk(CLOCK2_50,reset,1'b1,clk_i2c);  //10k I2C clock  
//clkgen #(100) my_i2c_clk(CLOCK2_50,reset,1'b1,myclk);  //piano clk  

I2C_Audio_Config myconfig(clk_i2c, KEY[0],FPGA_I2C_SCLK,FPGA_I2C_SDAT,audio_config_testbits,0,volume);

I2S_Audio myaudio(AUD_XCK, KEY[0], AUD_BCLK, AUD_DACDAT, AUD_DACLRCK, audiodata);

Sin_Generator sin_wave(AUD_DACLRCK, KEY[0], freq, audiodata);//

piano p1(.ps2_clk(PS2_CLK),.ps2_data(PS2_DAT),.clk(CLOCK2_50),.volume(volume),.freq(freq),.test(LEDR),.en(en));

//elec_piano ep(.clk(CLOCK2_50),.ps2_clk(PS2_CLK),.ps2_data(PS2_DAT),.freq(freq),.volume(volume));

endmodule
