
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module EXP1(

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output	reg	  [9:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [1:0]cin;


//=======================================================
//  Structural coding
//=======================================================
assign cin[0] = SW[0]; 
assign cin[1] = SW[1];

always @ (cin)
begin
	case(cin)
		0: begin LEDR[0] = SW[2];LEDR[1] = SW[3]; end
		1: begin LEDR[0] = SW[4];LEDR[1] = SW[5]; end
		2: begin LEDR[0] = SW[6];LEDR[1] = SW[7]; end
		3: begin LEDR[0] = SW[8];LEDR[1] = SW[9]; end
		default: begin LEDR[0] = SW[2];LEDR[1] = SW[3]; end
	endcase
end 

endmodule
