
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module EXP11(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// Video-In //////////
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_DIN,
	input 		          		ADC_DOUT,
	output		          		ADC_SCLK,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// IR //////////
	input 		          		IRDA_RXD,
	output		          		IRDA_TXD
);
wire [7:0]ascii_out;
wire enable;
wire [7:0]ascii;
assign ascii = ascii_out & {8{enable}};//{{7{enable}},enable}
wire [11:0]temp;
//=======================================================
//  REG/WIRE declarations
//=======================================================

//LEDR test signals
//asill code tests(keyboard module test)
light l1(.data(ascii_out),.enable(enable),.out_l(HEX0),.out_h(HEX1));

//keyboard control
exp08 keyb(CLOCK2_50,KEY[3:0],SW[9:0],ascii_out,enable,PS2_CLK,PS2_CLK2,PS2_DAT,PS2_DAT2);

//VGA control
charDisplay cd(CLOCK2_50,VGA_CLK,ascii,temp,VGA_BLANK_N,VGA_B,VGA_G,VGA_HS,VGA_R,VGA_SYNC_N,VGA_VS);

//test
//piture_control con(CLOCK2_50,VGA_CLK,ascii,temp,VGA_BLANK_N,VGA_B,VGA_G,VGA_HS,VGA_R,VGA_SYNC_N,VGA_VS);

//=======================================================
//  Structural coding
//=======================================================

endmodule
